### ISSUE TITLE
Add "latest" (generic) URLs for individual pages

### ISSUE THREAD

**Issue by tmysik** [karma-runner/karma-runner.github.com#28]
In NetBeans, we support Karma (you know that ;) and we would like to point users to Karma installation page. However, the URL currently contains Karma version [1] which is unfortunate since sooner or later, the page will be out-of-date. Could you please add **generic** URLs for the latest stable version, something like [2] or [3]?

Thanks for understanding,
Tomáš
[1] http://karma-runner.github.io/0.12/intro/installation.html
[2] http://karma-runner.github.io/latest/intro/installation.html
[3] http://karma-runner.github.io/stable/intro/installation.html

**Comment by Dignifiedquire** [comment]
Sure thing, I'm gonna take a look if I can get 
http://karma-runner.github.io/intro/installation.html to redirect to http://karma-runner.github.io/0.12/intro/installation.html which would make the urls even cleaner, as http://karma-runner.github.io/ already redirects to http://karma-runner.github.io/0.12/index.html

**Comment by tmysik** [comment]
@Dignifiedquire Thanks a lot!

**Comment by Dignifiedquire** [comment]
@tmysik the easiest way was to do http://karma-runner.github.io/latest/intro/installation.html should work now on all pages :) Enjoy

**Comment by tmysik** [comment]
@Dignifiedquire Works like a charm. Thanks a lot for a superfast fix! :+1:
