### ISSUE TITLE
Minor layout issue on the homepage.

### ISSUE THREAD

**Issue by kitsunde** [karma-runner/karma-runner.github.com#34]
Full width 13" mac using latest chrome.

<img width="1126" alt="screenshot 2015-11-18 21 34 52" src="https://cloud.githubusercontent.com/assets/48965/11242308/ea4c0b08-8e3b-11e5-8cb7-639d338d0ea1.png">

**Comment by Dignifiedquire** [comment]
Thanks for the report

**Comment by devoto13** [comment]
I can not reproduce this problem in the latest Chrome on 13" Mac now. Probably it was fixed in the meantime, hence closing the issue.
